#ifndef _GD_HAL_RCC_H
#define _GD_HAL_RCC_H

#include "gd32f4xx.h"

void __HAL_RCC_GPIOA_CLK_ENABLE();
void __HAL_RCC_GPIOB_CLK_ENABLE();
void __HAL_RCC_GPIOC_CLK_ENABLE();
void __HAL_RCC_GPIOD_CLK_ENABLE();
void __HAL_RCC_GPIOE_CLK_ENABLE();
void __HAL_RCC_GPIOF_CLK_ENABLE();
void __HAL_RCC_GPIOG_CLK_ENABLE();
void __HAL_RCC_GPIOH_CLK_ENABLE();
void __HAL_RCC_GPIOI_CLK_ENABLE();



#endif /* _GD_HAL_RCC_H */
